---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-cats
  template:
    metadata:
      labels:
        app: my-app-cats
    spec:
      imagePullSecrets:
      - name: secret-registry
      containers:
      - name: my-app-cats
        image: 700066115436.dkr.ecr.us-east-1.amazonaws.com/ecr_cats:catsv1
        #image: 700066115436.dkr.ecr.us-east-1.amazonaws.com/ecr_cats:catsv2   -> for version 2
        imagePullPolicy: Always
        ports:
          - containerPort: 80