apiVersion: v1
kind: Pod
metadata: 
  name: my-app-dogs
  labels:
    app: my-app-dogs
spec: 
  containers:
  - name: my-app-dogs
    image: 700066115436.dkr.ecr.us-east-1.amazonaws.com/ecr_dogs:dogsv1
    ports:
    - containerPort: 80
    